global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Worker metrics
  - job_name: "workers"
    static_configs:
      - targets: ["worker:9100"]
    metrics_path: "/metrics"
