global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "workers" # scraping worker metrics
    dns_sd_configs: # for docker containers
      - names: ["worker"]
        type: A
        port: 9100


  - job_name: "api"
    static_configs:
      - targets: ["localhost:8000"] # for docker container
